### ISSUE TITLE
data entry in config_spacy.json

### ISSUE THREAD

**Issue by NicoHood** [JustinaPetr/Weatherbot_Tutorial#10]
https://github.com/JustinaPetr/Weatherbot_Tutorial/blob/master/Full%20Code%20%5BLatest%20release%20of%20Rasa%20NLU%20and%20Rasa%20Core%5D/config_spacy.json#L4

I am wondering why this data entry was used here. It seems to be a) not relevant or b) missing in [the docs](https://nlu.rasa.com/config.html)

Thanks for the answer :)

**Comment by JustinaPetr** [comment]
Hey @NicoHood . Good catch! :) When I recorded the video, the format of defining the pipeline was slightly different and back then it was ok to define the data file inside the config - it was more useful for the sanity of the code and to easily keep track of where the data that is used for training is located. With the latest versions of Rasa NLU it is not necessary anymore so you are absolutely right that it is not really relevant now.
