### ISSUE TITLE
Unsupported pickle protocol

### ISSUE THREAD

**Issue by virajpwr** [JustinaPetr/Weatherbot_Tutorial#15]
I'm getting the following error when I run train_online.py file:

"ValueError: unsupported pickle protocol: 3"

Please let me know if there is any solution for this.

**Comment by JustinaPetr** [comment]
Hey @virajpwr. 

I guess you are using python 2.7? You get this error when Rasa Core tries to export a trained model as a pickle file. Python 2 uses pickle protocols 0,1,2 while Python 3 uses protocols 0,1,2,3,4 and defaults at 3 which is not supported in Python 2. The easiest solution would be to run it with Python 3.

**Comment by virajpwr** [comment]
Works on Python 3. Thank a million for your answer.
