### ISSUE TITLE
Dialogue_management_model.py runtime error

### ISSUE THREAD

**Issue by lakindu95** [JustinaPetr/Weatherbot_Tutorial#19]
```
Bot loaded. Type a message and press enter (use '/stop' to exit):

127.0.0.1 - - [2018-09-20 15:39:00] "POST /webhooks/rest/webhook?stream=true&token= HTTP/1.1" 200 154 0.212377
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/lakindugunasekara/Library/Python/2.7/lib/python/site-packages/rasa_core/channels/console.py", line 110, in record_messages
    for response in bot_responses:
  File "/Users/lakindugunasekara/Library/Python/2.7/lib/python/site-packages/rasa_core/channels/console.py", line 67, in send_message_receive_stream
    stream=True) as r:
AttributeError: __exit__
```

What could go wrong in this code?

**Comment by PravinrajV** [comment]
I am getting the same error.

**Comment by vigneshp826** [comment]
me as well :(

**Comment by JustinaPetr** [comment]
Hey @lakindu95 I am guessing this has to do something with Python 2.7. I would suggest running it in virtual env with python 3.6 and checking if the issues persists

**Comment by lakindu95** [comment]
Thanks for the reply @JustinaPetr In Pytohn 3.6, The published Rasa Core pip installation doesn't work directly. There is an incompatibility issue with Tensorflow 0.10 version. How ever if you install the github repo, removing the version for Tensorflow, it's working.

How ever regarding this issue, I tried using the starter pack
 https://github.com/RasaHQ/starter-pack-rasa-stack

And it works fine with python 2.7 well.

**Comment by lakindu95** [comment]
Closing this issue and referring to the duplicate issue. #17

**Comment by vigneshp826** [comment]
> Hey @lakindu95 I am guessing this has to do something with Python 2.7. I would suggest running it in virtual env with python 3.6 and checking if the issues persists

@JustinaPetr am using Python-3.5, but getting the same error.

**Comment by vigneshp826** [comment]
> Thanks for the reply @JustinaPetr In Pytohn 3.6, The published Rasa Core pip installation doesn't work directly. There is an incompatibility issue with Tensorflow 0.10 version. How ever if you install the github repo, removing the version for Tensorflow, it's working.
> 
> How ever regarding this issue, I tried using the starter pack
> https://github.com/RasaHQ/starter-pack-rasa-stack
> 
> And it works fine with python 2.7 well.

Hi @lakindu95 , can you pls explain more on how you resolved this issue neglecting the Starter-pack-restart-pack project.

**Comment by antoinecomp** [comment]
@vigneshp826 Maybe start using Python3.6 as suggested by Justina?

**Comment by arthi26** [comment]
@antoinecomp thank you for your reply. actually my issue solved by unsetting proxy details.

https://github.com/JustinaPetr/Weatherbot_Tutorial/issues/17#issuecomment-431326931

**Comment by vigneshp826** [comment]
@antoinecomp thank you for your reply. actually my issue solved by unsetting proxy details.

https://github.com/JustinaPetr/Weatherbot_Tutorial/issues/17#issuecomment-431326931
