### ISSUE TITLE
500 INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by mikebitsoko** [JustinaPetr/Weatherbot_Tutorial#22]
Ubuntu 18
----------------------
ERROR:rasa_core.processor:Encountered an exception while running action 'action_weather'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
ERROR:rasa_core.processor:500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/processor.py", line 324, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/actions/action.py", line 312, in run
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

**Comment by mikebitsoko** [comment]
-- Fixed

**Comment by vigneshp826** [comment]
@mikebitsoko could you please explain the solution for this issue?

**Comment by vigneshp826** [comment]
> -- Fixed

Hey @mikebitsoko ,Please provide the solution which worked for you, it would be helpful for other users.

**Comment by tarunmanchanda** [comment]
Hey, can anybody please provide the solution to this problem? @mikebitsoko
