### ISSUE TITLE
Error while running python dialogue_management_model.py

### ISSUE THREAD

**Issue by SreenijaK** [JustinaPetr/Weatherbot_Tutorial#23]
While running the file gives,
Traceback (most recent call last):
  File "train_online.py", line 39, in <module>
    run_weather_online(nlu_interpreter)
  File "train_online.py", line 32, in run_weather_online
    online.serve_agent(agent)
AttributeError: module 'rasa_core.training.online' has no attribute 'serve_agent'

I believe server_agent doesnt exisit in online now

**Comment by tapos12** [comment]
Similar problem now

**Comment by JustinaPetr** [comment]
Hey @SreenijaK, yes - this is due to the most recent changes to Rasa Core. I have pushed a fix for it to the repo :)
