### ISSUE TITLE
AttributeError: module 'rasa_core.training.online' has no attribute 'run_online_learning'

### ISSUE THREAD

**Issue by ankur17895** [JustinaPetr/Weatherbot_Tutorial#34]
**When i start model training using train_online.py I am getting  error specified below:**

AttributeError                            Traceback (most recent call last)
<ipython-input-1-6ab8bb463f02> in <module>()
            logging.basicConfig(level="INFO")
            nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/weathernlu')
--->        run_weather_online(nlu_interpreter)

<ipython-input-1-6ab8bb463f02> in run_weather_online(interpreter, domain_file, training_data_file)
                               epochs=200,
                               max_training_samples=300)				   
--->        online.run_online_learning(agent)
            return agent
      

AttributeError: module 'rasa_core.training.online' has no attribute 'run_online_learning'

**Comment by JustinaPetr** [comment]
Hey. Which version of Rasa Core are you running this with?

**Comment by ankur17895** [comment]
0.11.3

**Comment by JustinaPetr** [comment]
Oh, I see now :) With Rasa Core >0.11.3 there were a lot of improvements for online learning introduced. The latest code in this repo is updated for Rasa Core >0.11.3 that.s why you are getting the error. I would suggest you updating the Rasa Core version using
```
pip install -U rasa_core
```

which should pick up the changes and the error should be gone.

**Comment by ankur17895** [comment]
Thanks it is working now. :)
