### ISSUE TITLE
incompatibility shown in package dependency

### ISSUE THREAD

**Issue by gaurvipul** [JustinaPetr/Weatherbot_Tutorial#63]
While doing pip install from requirements.txt, got following dependency warnings...

tensorflow 1.12.0 has requirement numpy>=1.13.3, but you'll have numpy 1.13.1 which is incompatible.
rasa-nlu 0.14.1 has requirement boto3~=1.5, but you'll have boto3 1.4.4 which is incompatible.
rasa-nlu 0.14.1 has requirement coloredlogs~=9.0, but you'll have coloredlogs 7.3 which is incompatible.
rasa-nlu 0.14.1 has requirement klein~=17.10, but you'll have klein 17.2.0 which is incompatible.
rasa-nlu 0.14.1 has requirement matplotlib~=2.0, but you'll have matplotlib 1.5.3 which is incompatible.
rasa-nlu 0.14.1 has requirement requests~=2.20, but you'll have requests 2.14.2 which is incompatible.
rasa-nlu 0.14.1 has requirement scikit-learn~=0.20.2, but you'll have scikit-learn 0.19.1 which is incompatible.
rasa-nlu 0.14.1 has requirement simplejson~=3.13, but you'll have simplejson 3.11.1 which is incompatible.
rasa-nlu 0.14.1 has requirement six~=1.11, but you'll have six 1.10.0 which is incompatible.
rasa-nlu 0.14.1 has requirement tqdm~=4.19, but you'll have tqdm 4.11.2 which is incompatible.
rasa-nlu 0.14.1 has requirement typing~=3.6, but you'll have typing 3.5.3.0 which is incompatible.
rasa-core-sdk 0.12.1 has requirement coloredlogs~=10.0, but you'll have coloredlogs 7.3 which is incompatible.
rasa-core-sdk 0.12.1 has requirement ConfigArgParse~=0.13.0, but you'll have configargparse 0.12.0 which is incompatible.
rasa-core-sdk 0.12.1 has requirement flask~=1.0, but you'll have flask 0.12 which is incompatible.
rasa-core-sdk 0.12.1 has requirement requests~=2.20, but you'll have requests 2.14.2 which is incompatible.
rasa-core-sdk 0.12.1 has requirement six~=1.11, but you'll have six 1.10.0 which is incompatible.
rasa-core 0.13.0 has requirement coloredlogs~=10.0, but you'll have coloredlogs 7.3 which is incompatible.
rasa-core 0.13.0 has requirement fakeredis~=0.10.0, but you'll have fakeredis 0.8.2 which is incompatible.
rasa-core 0.13.0 has requirement fbmessenger~=5.0, but you'll have fbmessenger 4.3.1 which is incompatible.
rasa-core 0.13.0 has requirement flask~=1.0, but you'll have flask 0.12 which is incompatible.
rasa-core 0.13.0 has requirement gevent~=1.4, but you'll have gevent 1.2.1 which is incompatible.
rasa-core 0.13.0 has requirement jsonpickle~=1.0, but you'll have jsonpickle 0.9.4 which is incompatible.
rasa-core 0.13.0 has requirement networkx~=2.2, but you'll have networkx 1.11 which is incompatible.
rasa-core 0.13.0 has requirement numpy~=1.16, but you'll have numpy 1.13.1 which is incompatible.
rasa-core 0.13.0 has requirement packaging~=18.0, but you'll have packaging 17.1 which is incompatible.
rasa-core 0.13.0 has requirement pykwalify~=1.7.0, but you'll have pykwalify 1.6.0 which is incompatible.
rasa-core 0.13.0 has requirement requests~=2.20, but you'll have requests 2.14.2 which is incompatible.
rasa-core 0.13.0 has requirement scikit-learn~=0.20.0, but you'll have scikit-learn 0.19.1 which is incompatible.

**Comment by JustinaPetr** [comment]
Hey @gaurvipul. Thanks a lot for raising this! I have just updated the requirements.
