### ISSUE TITLE
bot doesn't respond properly

### ISSUE THREAD

**Issue by Swarnalathaa** [JustinaPetr/Weatherbot_Tutorial#65]
Hi,
I have followed the tutorial and managed to make the bot working. But sometimes the bot doesn't respond as expected( for example reply about the weather condition of the previously asked location/reply with weather condition when greet is done) or provides no reply. I have attached the responses of the bot below. Similarly after integrating with the slack I get the delayed response or no response back.

![bot](https://user-images.githubusercontent.com/34007219/52069386-ef281800-257e-11e9-9f55-3248f62ccbb4.PNG)

**Comment by antoinecomp** [comment]
Hi Swarna, considering what you shared on the screen 
1. Do you have the goodbye intent in your domain.yml file ?
2. Verify that it always understand your intents : make a script as several inputs.
3. If you added examples in data.json files make sure to run again train_init.py
4. Verify there is enough different examples in stories.md

For further help don't hesitate to share your Rasa Core version, Python version, Operating system (windows, osx, ...) and even the content of domain file or asking help on [the rasa forum](https://forum.rasa.com/c/getting-started-with-rasa).

**Comment by JustinaPetr** [comment]
I will close this for now :)
