### ISSUE TITLE
Getting error : ValueError: bad input shape (1, 3)

### ISSUE THREAD

**Issue by himanshuteotia** [JustinaPetr/Weatherbot_Tutorial#68]
These are my files screenshots :
![image](https://user-images.githubusercontent.com/10083136/52770153-5066e580-306d-11e9-805c-f1b76dc72042.png)

![image](https://user-images.githubusercontent.com/10083136/52770212-72606800-306d-11e9-8688-453765adfe94.png)

**Comment by himanshuteotia** [comment]
Error file
![image](https://user-images.githubusercontent.com/10083136/52770318-b8b5c700-306d-11e9-910e-9f507b0d9dd0.png)

**Comment by JustinaPetr** [comment]
@himanshuteotia Strange. Did you try retraining the models? (running nlu_model.py and dialogue_management_model.py scripts)?

**Comment by himanshuteotia** [comment]
Yes, I tried that 

first I ran the 'train_nlu' function then 'run_nlu' as mentioned in docs

**Comment by datA2Z** [comment]
downgrade  scikit-learn  0.20 to 0.19.1. and again train your model. That should solve the problem.

**Comment by cobusgreyling** [comment]
I had the same error, kept be busy for half a day. Solution for me was:
1. Install Anaconda
2. Created a virtual environment with Python 3.6 (I was 3.7) conda create -n rasa python=3.6.
3. conda activate rasa
4. All worked fine.  

So it seem you nee to use Python 3.6 with this list of requirements.  But run Anaconda virtual environment.  Much easier to manage.

**Comment by JustinaPetr** [comment]
Yes, you should use Python 3.6 (or earlier) with Rasa Stack for now as some dependencies are not yet updates for Python 3.7. I will add this to the readme :)

**Comment by himanshuteotia** [comment]
Thanks, guys.. after too many changes it's working now :+1:
