### ISSUE TITLE
tenserflow error

### ISSUE THREAD

**Issue by saurabhbidwai** [JustinaPetr/Weatherbot_Tutorial#7]
Could not find a version that satisfies the requirement tensorflow (from -r requirements.txt (line 29)) (from versions: )
No matching distribution found for tensorflow (from -r requirements.txt (line 29))

**Comment by HaziRushJay** [comment]
Had the same issue. Try installing x64 distribution of Python. Tensorflow needs x64 distribution [https://www.tensorflow.org/install/install_windows](url)
